sudo: false
language: node_js
node_js:
- '12'
branches:
  only:
  - master
script: make travis
before_deploy: make travis-deploy
env:
  global:
  - secure: EFxV6rmAOrTKHB/zdn40tC0N9wohjZ2licW7XDsBFCgAKPrHYexzlq49EvgcC6lilfamrHSA80bl2Rl9d2TPb1+0Xk5RKVrkb9B/xx0xxk3NWD2oY1LWxsxkOBlhGbMv+THNxm52mr9Os7THt+caLgR5rXMUmfjgMiG0YRTUPbxVIs/LBNht+hfO+z2q4R2LY5vR5JjhEjxc2VhQVCgiprxJvA3pUaa5X6nIAqhh12Re5xPUnM/hPZu4hLk1KLSzl1V9Q/c4zqBKxTezD/cW/maIEjVt/ZgihxgaXajHBNgpD+xDm/ndr2FaznkJA13i8MEiTYgKgDupVI58xIzdautX00gDRekh1ZdNtXijzjMGcx0l4rp4HUt/txI0PxKIBcyeaClSqFrshklUQlHsI7nX87f5I7VlD7oOoDOlNGnnN/05s1NbMKAvB5g3PilODCLKuCqEqhZrm/QPk5ROgeouB4Nun9AQp4oGw9qSzp17VNGRE0KAuYn62BEWdrVo1WJmjHohm8lwbIwACnGlHbKt7FSQyuUJOXFpR3HUIBNgGw6EnH0iKvP/8FyODsewOsoJpymGxQr8dacPzyAG0jwSFi79zGOCbPw7e9A6kmzQT6WU0lOMuPcft3PYoozlMh5KAbyjOyTWAnMnRw4BOAepypzQflub/6zlojfUfWA=
  - secure: 3wITXp82sqyq/FjS2JG08YqjYazQWshawUAP4YLUaitJpv3yQWFEl6mHaYHXxyaNxJgmyBZMCsz76Xv4bhHr3NsNfV2SMQlIarhPkMQCZuIEt3VihbfgS97GUwMvNcibkOUMSIKws1G4fUWcRHpv+UKAXf+FCpiY40MbK0NCFaKzOz9OtttUVk2ebkSgIJPgXAWYNMk9FCnbL+7ehsWTXjMH+kIUjBQqn8kmfvgNFKvFpzdnddHzTG33q2XjguUk9txqZ2got06w2MFcrLhF6FrWHORzAcKYU9lzQMrAKmazCmq7FzsZyCx7HHALN6ZhXd7VZTvtzQ2XZJ7I3v0CnjD4zwJCS0DZUpo6OVAjCwz6RH/Pb6AtJbeGyrBpwgBnr4Es0lC4y5gOet4tV2DGpLd5dEEu0UD1uLd7+r7i/BuoCZcGjfv/RrOb5fKg7iv63bCTNyWmVeCbw4EawZ4NxLnt10nKaDE1N+biUR6vNMXDZMaCNDcBwNXANGLSqEcM2QZO9gQVrXCieYiC6UFHCTab2hAUD7d41OG9BGXQg/CvqfUFyOcBhASjmQzEXwYL+dvtoJN5NEuWzAIl2pjJhjlgYtLhHjPMroIwpmUhyY8556HVir/rMj307nld5+8y39+JgQ3tLtFyn7xEn7RrIxEgKHfU7He4IIKZQDP5LZs=
