sudo: false
language: node_js
node_js:
  - "12"
branches:
  only:
    - master
script: make travis
before_deploy: make travis-deploy
env:
  global:
    - secure: xLvekyuMU34JaCzL7EWmhOQW1zg/XgCCkkkg8IH99bZiE2ZFpG4UcKSu6/rsUTVoejn+45CuZx1f0MIruf5UDRj48ruycD6XTqca4eGCWfJsx0iyVmRnexrMa//RW5Po3oAZHiZG99TJEbBOlhbAjxMrZl3BHmTH1p6PEQYEimUbIfOwHBOgCn+4EyoMCw7zGfCrNaSWyRToS0oPeLdZIaPkQ8jDR1iSYACotNeL9Cik9iLv3W6AWUdIbGSEBjKEbW8lum7g8FIcfJ/VxnwphU35Zu/73p9d7/ovn2yhll5yFZEB9pb13pEX27NEZbUiy/BeBKihJxZvjXEQmvtXNs4aZFiooNjkQghoxHd44cDev+VvqqxYlVmJlwJvhqemLZdInQLjYpZHPlWyChR1w9PHBB8WygpfmJup2ABpP86MVUhMR2M5n3hdk70Z6Dzd1L6zOdXfCFe1TjueEMXtm0ISXGMQd2NM+FO6TdcHvYEVk+womr1cq7kVi5sOTDYC+YRoyBvQEzltjNzLNa8MHfQv/oDxw5mS/B65zJ5uWU9Xd9Xyq84Tm9BdH+xv5HLB2CJlvRwW4f/qP7oNBhAa79pfmk791BrbQ2LIYpNXlCGoy7cs0SIaxX94wjxpGFEkQLOKm7k3wM6wA3d6sg+B7gtU4A5puHLTyUJecllJdvk=
    - secure: OK3Wi4RR14JMZwj40RB6QPQSZF1wNfRJwKorPNN8vfc+/sgZZ861yCiclnXei6CMZx3Fupz7EqMUDK+6lTV7tk3VyagYL+9qR2qPl044Rah9nF3qH0a0wDPH4sQfUzJQ4bfg5V9/9iv5p3vXbdtBtSeKLc6j0N88AC5dsw7TGJRMgruS9Kmt0pL2JxwlU5QHau1/Abr8hzjAOee9S2+TiJGRE9E9TDBHdWR0j3fB8f2TV28Y2PDXzFfaQm8canAJZBNeyV7l+CiAVdyVP2YTW2fOFMn4USjxhyCdPzdb17tyPUlryW+SpalpfKun4Uew8oHLQ3m+mxsGWhOsEY7L7gqGruuzUFeaLGsadqSZ9ha3ZXFTfievdpbdkukZssf9MLAnN5XYbaTHfuW1iqjY0vxJJmCH3nhc8vkhGsTQROtnjqOP81rVmOoly+fq8+0Hg5ybPbPk3fIUK9Y4VnmS0A42DDKbaveQzpJT3ACh5Ubnwd2StrXgHElkFYhEuK1FYGLR6DUC7GgoK4p26TY9YITnxGIclGN/V1hmrTR9P83xTGbUlTHwg6hla73XC09JSIJ/2Pj6HhbrGVin2KAyItUPSBbnpko898H0cgTZZzhmLa19uNVWslklAl5Ct9iTPI8pbxzTMaUU9Z8ixFpV25cIvQGJXxTJK/hrCy+oRLw=
